import gta from "../img/gta-v-big.webp"


const Games = [
	{
		'id': 1,
		'title': 'Grand Theft Auto V',
		'img': gta,
		'reviews': '6,100',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 2,
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 2,
		'title': 'Cyberpunk 2077: Phantom Liberty',
		'img': 'https://images.gog-statics.com/45a284386e693f1576b96d98a0023a7905d3956c6f9aa913d3fe5d09a5994bee_product_card_v2_mobile_slider_450.jpg',
		'reviews': '6,200',
		'date': 'September 26, 2023',
		'genres': 'Role-playing - Action - Sci-fi',
		'star': 4,
		'video': 'https://www.youtube.com/embed/4QGhsGvws58?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 3,
		'title': 'The Witcher 3: Wild Hunt - Complete Edition',
		'img': 'https://images.gog-statics.com/71d71c40052877a42c096b8230c71856a560d42132208cfa8e719243b5c6626b_product_card_v2_mobile_slider_639.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/JY6Bjij7XXE?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 4,
		'title': 'F1® 2020',
		'img': 'https://games-all.net/uploads/posts/2023-01/1673956495_f1.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/wF0vF1uXXYU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 5,
		'title': 'Minecraft: Java Edition 1.19.2 ',
		'img': 'https://games-all.net/uploads/posts/2023-01/1674942531_minecraft-java-edition-2.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/MmB9b5njVbA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 6,
		'title': 'World of Tanks',
		'img': 'https://games-all.net/uploads/posts/2019-08/1566776279_7.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 3,
		'video': 'https://www.youtube.com/embed/J2kSkF4QEe0?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 7,
		'title': 'Act of War Gold Edition: Direct Action',
		'img': 'https://games-all.net/uploads/posts/2023-01/1674938377_act-of-war-gold-edition.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/tNExOOxlchI?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 8,
		'title': 'Lost Ark',
		'img': 'https://games-all.net/uploads/posts/2019-11/thumbs/1573858391_12.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/m0Ohi0g3Q8g?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 9,
		'title': 'Hello Neighbor 2 Alpha 1.5 ',
		'img': 'https://games-all.net/uploads/posts/2023-02/thumbs/hello-neighbor-2.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/ANwsrrQSE88?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 10,
		'title': 'NEXT RP  ',
		'img': 'https://games-all.net/uploads/posts/2020-06/thumbs/1591833632_4.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/5FcWiyGcNiQ?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},

	{
		'id': 11,
		'title': 'Fortnite',
		'img': 'https://games-all.net/uploads/posts/2015-07/1436356452_fortnite.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/PhpNnd1FITU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 12,
		'title': 'Far Cry 5',
		'img': 'https://games-all.net/uploads/posts/2017-12/thumbs/1513625240_far-cry-5.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/a_8THGId85U?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 13,
		'title': 'Football Manager 2019 ',
		'img': 'https://games-all.net/uploads/posts/2019-02/thumbs/1549093465_football-manager-2019.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/nP6Osa26_7g?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 14,
		'title': 'Oriental Empires  ',
		'img': 'https://games-all.net/uploads/posts/2018-01/thumbs/1515397324_oriental-empires.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/0mDDuU24F6c?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 15,
		'title': 'Dragon\'s Lair 2: Time Warp   ',
		'img': 'https://games-all.net/uploads/posts/2018-01/thumbs/1514908250_dragons-lair-2-time-warp.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/HzCJ5XInUqA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 16,
		'title': 'Gabelstapler 2014    ',
		'img': 'https://games-all.net/uploads/posts/2018-01/thumbs/1515253498_gabelstapler-2014.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/jWaX23MZ0Ag?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 17,
		'title': 'Ski World Simulator    ',
		'img': 'https://games-all.net/uploads/posts/2017-12/thumbs/1514116443_ski-world-simulator.png',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 3,
		'video': 'https://www.youtube.com/embed/EVsqQDdf9_Q?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 17,
		'title': 'Marvel vs. Capcom: Infinite',
		'img': 'https://games-all.net/uploads/posts/2017-12/thumbs/1513396931_marvel-vs.-capcom-infinite.png',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/L-8a6P7YKVA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 18,
		'title': 'Рождественские Истории 6: Маленький Принц ',
		'img': 'https://games-all.net/uploads/posts/2017-12/thumbs/1513396627_christmas-stories-6-a-little-prince.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/So-RJHuxqHw?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 19,
		'title': 'Killer Instinct ',
		'img': 'https://games-all.net/uploads/posts/2017-12/thumbs/1513396329_killer-instinct.png',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/3LIL_MCJSoI?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 20,
		'title': 'My Summer Car  ',
		'img': 'https://games-all.net/uploads/posts/2017-01/thumbs/1484106406_my-summer-car.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/xXwYBapZun8?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 21,
		'title': 'PAYDAY 3',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-08/1692730116_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/dc5gw3ctb0o?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 22,
		'title': 'Фростпанк',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665886658_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 2,
		'video': 'https://www.youtube.com/embed/UxTxUL_8VkA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 23,
		'title': 'Forza Motorsport 2023',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-06/1686512872_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/4_y255J9lmQ?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 24,
		'title': 'Mount & Blade 2 Bannerlord',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1664559867_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 5,
		'video': 'https://www.youtube.com/embed/d9Gr_f_I2QA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 25,
		'title': 'Зе Ласт оф Ас Парт 1 Ремейк',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-12/1670560415_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/Zf5xOsXXFY8?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 26,
		'title': 'Starfield (Старфилд)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1664725416_starfield.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/H26Dtgbsfzw?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 27,
		'title': 'Crusader Kings 3 (III)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1663162167_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/YlOXhOxEum0?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 28,
		'title': 'No Mans Sky',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-06/1686207755_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/h3HphgSn0o4?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 29,
		'title': 'Rust',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665236926_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/LGcECozNXEw?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 30,
		'title': 'Балдурс Гейт 3',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-08/1691082570_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/XuCfkgaaa08?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 31,
		'title': 'Рэтчет и Кланк: Рифт Апарт',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-05/1685464989_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/i_jZ3BV6Adc?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 32,
		'title': 'Biomutant',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-09/1694011462_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/73vSguCeJl0?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 33,
		'title': 'Дум Этернал',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-04/1680866462_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/xXwYBapZun8?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 34,
		'title': 'Saints Row 2022',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1663272450_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/xXwYBapZun8?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 35,
		'title': 'EA Sports FC 24 (FIFA 24)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-07/1689267289_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/DYB02N5aJec?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 36,
		'title': 'FIFA 23 (ФИФА 23)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1663619850_library_600x900_2x-12.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/o3V-GvvzjE4?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 37,
		'title': 'Фар Край 6',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668462149_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/wzFLmoDyemA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 38,
		'title': 'Steel Division 2',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1667205596_library_600x900_2x.jpeg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/pN7LFy4o6HU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 39,
		'title': 'The Dark Pictures: The Devil In Me',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1664725624_the-dark-pictures-the-devil-in-me.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/rN3-X3W27U4?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 40,
		'title': 'Ведьмак 3 Дикая Охота',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668378880_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/nBT2SP21f3Q?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 41,
		'title': 'Resident Evil 2 Remake',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665493167_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/xXwYBapZun8?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 42,
		'title': 'Стрит Файтер 6',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-05/1685106790_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/1INU3FOJsTw?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 43,
		'title': 'Хэрайзн Зироу Дон',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668563853_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/joLIEHwPOqw?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 44,
		'title': 'Sackboy: A Big Adventure',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1664479696_library_600x900_2x-2.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/MAaEqyE_Hfg?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 45,
		'title': 'Анчартед 4',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1663288749_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/PH8g_BoKB-w?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 46,
		'title': 'Герои Меча и Магии 5',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668464288_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/KolaL2g0bug?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 47,
		'title': 'Вольфенштейн Зе Нью Ордер',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668462412_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/l5Jsj3fWfDM?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 48,
		'title': 'Вотч Догс 1',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668464159_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/uhOnXqaTtlg?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 49,
		'title': 'Драгон Эйдж Инквизиция',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-07/1688596432_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/7xn6_hcBo9Y?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 50,
		'title': 'Финал Фэнтези 15',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-07/1689075930_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/ZFFmieoN-D?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 51,
		'title': 'Дизонорд 1',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668463543_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/I0fDTytPtgA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 52,
		'title': 'ФОЛЛАУТ 4',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668124261_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/0lWNdcbq3EU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 53,
		'title': 'Мафия 1',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668731419_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/VP48fer41YI?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 54,
		'title': 'Макс Пейн 3',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-07/1688595894_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/q6a8t3zL70A?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 55,
		'title': 'Дарк Соулс 3 (III)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-04/1681158333_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/ZXbPz8Jrkwg?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 56,
		'title': 'Миррорс Эдж Каталист',
		'img': 'https://itorrents-igruha.org/uploads/posts/2015-11/1446421411_37537483.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/7V775w4WR8Y?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 57,
		'title': 'Южный парк: Расколотый, но целый',
		'img': 'https://itorrents-igruha.org/uploads/posts/2017-08/1501809541__cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/_0LJ6wxSVGU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 58,
		'title': 'Зе Элдер Скролс 4 Обливион',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-06/1687444427_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/qJnnPh44Rlo?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 59,
		'title': '',
		'img': '',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/ZFFmieoN?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 60,
		'title': 'Дед Спейс 2',
		'img': 'https://itorrents-igruha.org/uploads/posts/2015-11/1446747448_dead-space-2_us_esrb_pc.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/z7Qy_4sWs3I?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 61,
		'title': 'Дед Спейс 1',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668463819_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/boRxhOjwiQ?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 62,
		'title': 'Вольфенштайн 2 Зе Нью Кэласоc',
		'img': 'https://itorrents-igruha.org/uploads/posts/2021-03/1615135354_screenshot_5.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/Tzeh7Z9vZHI?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 63,
		'title': 'Бордерлендс 3',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-03/1679614466_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/oouXu-fndps?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 64,
		'title': 'Ниер Автомата',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665239638_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/z7Qy_4sWs3I?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 65,
		'title': 'ФИФА 18',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-12/1670187539_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/l1FJfr_spJQ?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 66,
		'title': 'Резидент Эвил 8 Виладж',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-04/1681137326_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/smX4W_upPME?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 67,
		'title': 'Ниох 1',
		'img': 'https://itorrents-igruha.org/uploads/posts/2021-12/1640615986_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/_9PIVYW8u20?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 68,
		'title': 'Стар Варс Джеди Фален Ордер',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-04/1681755857_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/FAVB6F75rME?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 69,
		'title': 'Джаст Каус 4',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-07/1688408703_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/sRPJa94rTpU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 70,
		'title': 'Ассасин Крид Вальгалла',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665860526_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/L_OIRHyQOv4?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 71,
		'title': 'Элден Ринг',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665700897_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/gwdcGPxfDYY?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 72,
		'title': 'Форспокен',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1664725010_forspoken.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/Tku_2N6yhgc?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 73,
		'title': 'Готэм Найтс',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1664722058_gotham-knights.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/VSJTK8-R_sk?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 74,
		'title': 'Хогвартс Наследие',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1664820030_hogwarts-legacy.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/aOx7D1PSt9A?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 75,
		'title': 'Тайни Тина’эс Вандэландз',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-04/1682032108_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/3gJgj2ngCyA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 76,
		'title': 'Дед Спейс Ремейк (2023)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1664901843_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/96yUNw2zfW4?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 77,
		'title': 'Стар Варс Джеди Сурвайвал',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-04/1680950982_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/_F6YBwIPzmk?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 78,
		'title': 'Марвелэс Спайдермен Ремастер',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665101965_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/wQkAfmvjWgs?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 79,
		'title': 'Биошок Инфинити',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-03/1679845011_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/uB9yYfKq4ZA?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 80,
		'title': 'Minecraft Legends',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-03/1677622819_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/1JSjZqV-YK8?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 81,
		'title': 'Prey 2017',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-08/1691143864_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/64REEmgQoCQ?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 82,
		'title': '',
		'img': '',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/z7Qy_4sWs3I?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 84,
		'title': 'F1 Manager 2023',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-05/1684919458_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/896qC-7x9Mg?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 85,
		'title': 'Assassins Creed 4 Black Flag',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-12/1670983093_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/OwsotWkpSlU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 86,
		'title': 'Scorn',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1664212433_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/ufnepZBpqlc?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 87,
		'title': 'Дизонорд 2',
		'img': 'https://itorrents-igruha.org/uploads/posts/2021-04/1619462647_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/zDWtoWBU3Ng?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 88,
		'title': 'Фар Край 5',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668464672_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/HimWP4Q8qg4?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 89,
		'title': 'Need for Speed Carbon',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668466450_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/aLTMTguEKps?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 90,
		'title': 'Need for Speed Payback',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-06/1687175411_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/SGBD33ASgTo?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 91,
		'title': 'Death Stranding Directors Cut',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-09/1664391657_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/6tgsz7WbidU?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 92,
		'title': 'Need for Speed Unbound',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665072445_library_600x900_2x.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/H2Y8XCe7F9E?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 93,
		'title': 'Dead Island 2',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-12/1670961819_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/aKFXvXjhBT8?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 94,
		'title': 'Shadow of the Tomb Raider - Definitive Edition',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665424139_library_600x900_2x-2.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/GJprOON79Ig?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 95,
		'title': 'The Dark Pictures Anthology Man of Medan',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1664612841_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/4ju_osH5k6w?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 96,
		'title': 'Ведьмак 2 (The Witcher 2)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668385404_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/iRKasf_wN1M?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 97,
		'title': 'Assassins Creed 2',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-07/1689074161_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/R20-MOOZPpY?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},

	{
		'id': 98,
		'title': 'A Plague Tale Requiem',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-10/1665698485_a-plague-tale-requiem.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/aaT4Q4NGm-A?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 99,
		'title': 'Total War Attila',
		'img': 'https://itorrents-igruha.org/uploads/posts/2023-07/1688652170_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/xLZAv0y0J94?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},
	{
		'id': 100,
		'title': 'ГТА Сан Андреас (GTA San Andreas)',
		'img': 'https://itorrents-igruha.org/uploads/posts/2022-11/1668124427_cover.jpg',
		'reviews': '6,300',
		'date': '2013-09-17',
		'genres': 'Action, Adventure',
		'star': 4,
		'video': 'https://www.youtube.com/embed/daw8xhaGj2s?autoplay=1&mute=1',
		'descr': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at commodi doloremque eum expedita fugiat harum illum itaque laborum mollitia, nemo quisquam quos reiciendis saepe velit. Accusamus adipisci aliquid consequatur consequuntur corporis deleniti et eum eveniet excepturi inventore molestiae mollitia nam natus odio, omnis possimus praesentium qui, repudiandae unde voluptate.'
	},




]


export { Games }